---
users: []

# From https://www.schedmd.com/downloads.php
slurm_version: 19.05

slurm_cluster_name: cluster
slurm_control_machine: mgmt

slurm_partitions:
  - name: compute
    nodelist: ALL
    default: YES

filesystem_target_address: fileserver
# TODO Make this a map for each cloud provider
filesystem_mount_point: /

ansible_pull_repo: https://github.com/ACRC/slurm-ansible-playbook.git

software_install_dir: /mnt/{{ filesystem_mount_point }}
