---
users: []

# From https://www.schedmd.com/downloads.php
slurm_version: 17.11

slurm_cluster_name: cluster
slurm_control_machine: mgmt

slurm_partitions:
  - name: compute
    nodelist: ALL
    default: YES

filesystem_target_address: fileserver
filesystem_mount_point: /shared

ansible_pull_repo: https://github.com/ACRC/slurm-ansible-playbook.git
ansible_pull_branch: citc2
