---

slurm_accounting_db_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits') }}"

slurm_packages:
  - slurmctld
  - slurmdbd

slurm_role: mgmt

slurm_elastic:
  oracle:
    config_directory: /home/slurm/.oci/

install_packages:
  - xorg-x11-xauth

monitoring_role: master
