---

- hosts: compute
  tasks:
    - name: disable SELinux
      selinux:
        state: disabled

- hosts: compute
  roles:
    - dhcp
    - filesystem
    - ssh
    - epel
    - security-updates
    - ntp
    - sssd
    - slurm
    - monitoring
