---

- hosts: compute
  tasks:
    - name: install libselinux-python
      package:
        name: libselinux-python
        state: present
    - name: disable SELinux
      selinux:
        state: disabled

- hosts: compute
  roles:
    - citc_user
    - filesystem
    - ssh
    #- security-updates
    - ntp
    - sssd
    - lmod
    - packages
    - mpi
    - slurm
    - monitoring
