---

- hosts: compute
  tasks:
    - name: disable SELinux
      selinux:
        state: disabled

- hosts: compute
  tasks:
    - name: pre-install packages we will need
      package:
        state: present
        name:
          - nfs-utils
          - ntp
          - sssd
          - telegraf

- hosts: compute
  roles:
    - dhcp
    - filesystem
    - ssh
    - security-updates
    - ntp
    - sssd
    - slurm
    - monitoring
