---

- name: install virtualenv
  package:
    name: python-virtualenv
    state: present

- name: install easybuild
  pip:
    name:
      - easybuild
    virtualenv: /opt/easybuild
    virtualenv_command: /usr/bin/python2 -m virtualenv
