---
- name: install Python 3.6
  yum:
    name:
      - python36
      - python36-pip
      - python36-setuptools
    state: installed

- name: install OCI tools
  pip:
    name:
      - oci
      - oci-cli
      - PyYAML
    virtualenv: /opt/oci
    virtualenv_command: /bin/python36 -m venv

- file:
    path: "{{ slurm_elastic.oracle.config_directory }}"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: copy OCI private key
  copy:
    src: /home/opc/oci_api_key.pem
    dest: "{{ slurm_elastic.oracle.config_directory }}/oci_api_key.pem"
    owner: slurm
    group: slurm
    mode: 0400

- name: configure OCI config file
  copy:
    src: /home/opc/config
    dest: "{{ slurm_elastic.oracle.config_directory }}/config"
    owner: slurm
    group: slurm
    mode: 0400

- file:
    path: /etc/citc
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: copy mgmt_shape.yaml
  copy:
    src: /home/opc/mgmt_shape.yaml
    dest: /etc/citc/mgmt_shape.yaml
    owner: slurm
    group: slurm
    mode: 0744

- name: copy shapes.yaml
  copy:
    src: /home/opc/shapes.yaml
    dest: /etc/citc/shapes.yaml
    owner: slurm
    group: slurm
    mode: 0744

- name: configure startnode script
  template:
    src: startnode.j2
    dest: /usr/local/bin/startnode
    mode: 0755
  notify: restart slurmctld

- name: configure stopnode script
  template:
    src: stopnode.j2
    dest: /usr/local/bin/stopnode
    mode: 0755
  notify: restart slurmctld

- name: configure update_config script
  template:
    src: update_config.j2
    dest: /usr/local/bin/update_config
    mode: 0755

- name: create cloud-init bootstrap script
  copy:
    content: |
      #! /bin/bash

      date

      yum install -y ansible git
      cat > /root/hosts <<EOF
      [compute]
      $(hostname -f)
      EOF
      time python -u /usr/bin/ansible-pull --url=https://github.com/ACRC/slurm-ansible-playbook.git --checkout=ldap --inventory=/root/hosts compute.yml >> /root/ansible-pull.log

      date
    dest: /home/slurm/bootstrap.sh
    owner: slurm
