---

- name: install nginx
  include_role:
    name: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: webui.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          server1:
            listen:
              listen_localhost:
                port: 80
                opts:
                  - default_server
            root: /opt/webui
            server_name: localhost
            error_page: 500 502 503 504 /500.html
            reverse_proxy:
              locations:
                default:
                  location: /
                  try_files: $uri @proxy_to_app
                backend:
                  location: "@proxy_to_app"
                  proxy_set_header:
                    header_x_forwarded_for:
                      name: X-Forwarded-For
                      value: $proxy_add_x_forwarded_for
                    header_x_forwarded_proto:
                      name: X-Forwarded-Proto
                      value: $scheme
                    header_host:
                      name: Host
                      value: $http_host
                  proxy_redirect: off
                  proxy_pass: http://app_server
                error:
                  location: /500.html
                  root: /opt/webui
        upstreams:
          app_server:
            name: app_server
            servers:
              gunicorn:
                address: unix:/run/gunicorn.sock
                port: 8080
                health_check: fail_timeout=0

- name: install GCC
  package:
    name: gcc
    state: present

- name: install Python3 headers
  package:
    name: python3-devel
    state: present

- name: install webui
  pip:
    name:
      - django
      - gunicorn
      - mysqlclient
    virtualenv: /opt/webui_venv
    virtualenv_command: /bin/python3 -m venv
  register: webui_venv

- name: checkout webui
  git:
    repo: git://github.com/milliams/citc-webui.git
    dest: /opt/webui
    version: master

- name: Create webui group
  group:
    name: webui

- name: Create the webui user
  user:
    name: webui
    group: webui

# TODO make checkout readable only by correct user

- name: install gunicorn service file
  copy:
    src: gunicorn.service
    dest: /etc/systemd/system/gunicorn.service

- name: install gunicorn socket file
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/gunicorn.socket

- name: start and enable gunicorn
  systemd:
    name: gunicorn
    state: started
    enabled: yes
    daemon_reexec: yes

- name: create webui database
  mysql_db:
    name: webui
    state: present

- name: create webui MySQL user
  mysql_user:
    name: webui
    password: "{{ webui_database_password }}"
    priv: 'webui.*:ALL'
    state: present

# TODO create secret key file https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/#secret-key

- name: create webui mysql config
  template:
    src: my.cnf.j2
    dest: /etc/citc/webui.my.cnf
    owner: webui
    group: webui
    mode: "660"

- name: open HTTP port in firewall
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify:
    - restart firewalld
