---
- name: Download and unarchive Packer.
  unarchive:
    src: https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/packer

- name: ser permissions on packer
  file:
    path: /usr/local/bin/packer
    mode: u=rwx,g=rx,o=rx

- name: create packer directory
  file:
    path: /etc/citc/packer/
    state: directory
    mode: 0755

- name: copy in packer-build
  copy:
    src: packer-build.json
    dest: /etc/citc/packer/packer-build.json

- name: copy in config 
  template:
    src: config.json.j2
    dest: /etc/citc/packer/config.json

- name: copy in packer run script
  template:
    src: run-packer.sh.j2
    dest: /usr/local/bin/run-packer

# run packer
