---
- name: Ensure unzip is installed.
  package: name=unzip state=present

- name: Download and unarchive Packer.
  unarchive:
    src: https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/packer

- name: set permissions on packer
  file:
    path: /usr/local/bin/packer
    mode: u=rwx,g=rx,o=rx

- name: create packer directory
  file:
    path: /etc/citc/packer/
    state: directory
    mode: 0755

- name: copy in packer-build
  copy:
    src: packer-build.json
    dest: /etc/citc/packer/packer-build.json

- name: load the startnode config
  include_vars:
    file: /etc/citc/startnode.yaml
    name: startnode_config

- name: copy in packer ansible run script
  template:
    src: run_ansible.sh.j2
    dest: /etc/citc/packer/run_ansible.sh

- name: copy in packer extra run script template (no force overwrite)
  copy:
    src: compute_image_extra.sh
    dest: /home/citc/compute_image_extra.sh
    force: no
    owner: citc
    group: citc

- name: install oci-cli
  package:
    name: python36-oci-cli
    state: present
  when: ansible_local.citc.csp == "oracle"

- name: "[oracle] get image OCIDs"
  command: "oci --config-file=/home/slurm/.oci/config compute image list --compartment-id={{ startnode_config.compartment_id }}"
  register: oci_images
  when: ansible_local.citc.csp == "oracle"

- name: "[oracle] get ID of OCI non-GPU image"
  set_fact:
    oci_non_gpu_image_id: "{{ oci_images.stdout | from_json | json_query(jmesquery) }}"
  vars:
    jmesquery: 'data[?"operating-system"==`"Oracle Linux"` && "operating-system-version"==`"7.7"` && !contains("display-name", `GPU`)] | [0].id'
  when: ansible_local.citc.csp == "oracle"

- name: "[oracle] get ID of OCI GPU image"
  set_fact:
    oci_gpu_image_id: "{{ oci_images.stdout | from_json | json_query(jmesquery) }}"
  vars:
    jmesquery: 'data[?"operating-system"==`"Oracle Linux"` && "operating-system-version"==`"7.7"` && contains("display-name", `GPU`)] | [0].id'
  when: ansible_local.citc.csp == "oracle"

- name: copy in config
  template:
    src: config.json.j2
    dest: /etc/citc/packer/config.json

- name: copy in packer run script
  template:
    src: run-packer.sh.j2
    dest: /usr/local/bin/run-packer

- name: set permissions on run-packer
  file:
    path: /usr/local/bin/run-packer
    mode: u=rwx,g=rx,o=rx

- name: run packer to build first image
  command: /usr/local/bin/run-packer
  register: packer_result
  changed_when: "packer_result.rc == 0"
  failed_when: "packer_result.rc != 0"
