---

- name: install sssd
  package:
    name:
      - sssd
      - nss-tools

- name: copy CA cert to trust anchors
  copy:
    src: "{{ ca_cert}}"
    dest: /etc/pki/ca-trust/source/anchors/389-ds-cert.crt
    remote_src: yes

- name: update CA trust anchors
  command: update-ca-trust # noqa 301

- name: enable SSSD auth in PAM
  command: authconfig --enablesssdauth --update # noqa 301

- name: copy sssd config template
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  notify: restart sssd

- name: start service sssd
  service:
    name: sssd
    state: restarted
    enabled: yes
