---

- name: install sssd
  package:
    name=sssd

- name: import CA cert into openldap cert store
  command: certutil -A -d /etc/openldap/certs -n ca_cert -t "C,," -i "{{ mgmt_crt.ca_cert if mgmt_crt is defined else '/tmp/CA.crt' }}" # noqa 301

- name: enable SSSD auth in PAM
  command: authconfig --enablesssdauth --update # noqa 301

- name: copy sssd config template
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  notify: restart sssd

- name: start service sssd
  service:
    name: sssd
    state: restarted
    enabled: yes
