---
- name: disable SELinux
  selinux:
    state: disabled

- name: make base home directory
  file:
    path: /mnt{{ filesystem_mount_point }}/home
    state: directory

- name: Create webui group
  group:
    name: usermgmt

- name: create home dir creation script
  copy:
    src: create_home_dir.sh
    dest: /usr/local/libexec/create_home_dir
    mode: go=r,u=rwx
    group: usermgmt
  register: create_home_dir

- name: Add create_home_dir for sudoers
  copy:
    content: |
      %usermgmt ALL=(root) NOPASSWD: {{ create_home_dir.dest }}
    dest: /etc/sudoers.d/92-webui-create_home_dir
    validate: /usr/sbin/visudo -cf %s

- name: create ssh key setting script
  copy:
    src: set_ssh_key.sh
    dest: /usr/local/libexec/set_ssh_key
    mode: go=r,u=rwx
    group: usermgmt
  register: set_ssh_key

- name: Add set_ssh_key for sudoers
  copy:
    content: |
      %usermgmt ALL=(root) NOPASSWD: {{ set_ssh_key.dest }}
    dest: /etc/sudoers.d/92-webui-set_ssh_key
    validate: /usr/sbin/visudo -cf %s

- name: copy in LDAP add user script
  template:
    src: add_user_ldap.j2
    dest: /usr/local/sbin/add_user_ldap
    mode: 0700

- name: create cluster-internal SSH key for OCI user
  user:
    name: opc
    generate_ssh_key: yes
    ssh_key_comment: oci cluster internal generated by ansible
  register: oci_ssh_key
  when:
    - "'management' in group_names"
    - ansible_local['citc']['csp'] == "oracle"

- name: Set authorized key taken from file
  authorized_key:
    user: opc
    state: present
    key: "{{ oci_ssh_key.ssh_public_key }}"
  when: ansible_local['citc']['csp'] == "oracle"
