---
- name: install scl-utils
  package:
    name: scl-utils

- name: install SCL repo
  package:
    name: centos-release-scl
  when: ansible_distribution == 'CentOS'

- name: install scl repo
  yum_repository:
    name: scl
    description: SCL
    baseurl: http://mirror.centos.org/centos/7/sclo/x86_64/rh/
  when: ansible_distribution == "Amazon"

- name: install devtoolset
  package:
    name: devtoolset-8
